/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package clienttudien;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.lang.Exception;

/**
 *
 * @author Administrator
 */
public class Main extends javax.swing.JFrame {

    KetNoi connect = new KetNoi("localhost", "root", "", "csdl");
    DefaultListModel dm = new DefaultListModel();
    ResultSet result = null;
    Statement state = null;
    String table = "engvie";
    String id;
    String TuGoc;
    String Nghia;
    String search = "";
    String search2 = "";
    String sql = "";
    String kiemtra = "";
    String tDich = "";

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        loadDuLieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbNhomTim = new javax.swing.ButtonGroup();
        txtText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsDanhSach = new javax.swing.JList();
        btnEV = new javax.swing.JLabel();
        btnVE = new javax.swing.JLabel();
        btnVV = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbNghia = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnDich = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương Trình Tra Từ Điển Trực Tuyến");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTextCaretUpdate(evt);
            }
        });
        getContentPane().add(txtText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 220, -1));

        lsDanhSach.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lsDanhSach.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsDanhSachValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lsDanhSach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 154, 220, 300));

        btnEV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Eng-Viet2.png"))); // NOI18N
        btnEV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEVMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEVMouseExited(evt);
            }
        });
        btnEV.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEVMouseMoved(evt);
            }
        });
        getContentPane().add(btnEV, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        btnVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/VIet-Eng1.png"))); // NOI18N
        btnVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVEMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVEMouseExited(evt);
            }
        });
        btnVE.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnVEMouseMoved(evt);
            }
        });
        getContentPane().add(btnVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        btnVV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Viet-Viet1.png"))); // NOI18N
        btnVV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVVMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVVMouseExited(evt);
            }
        });
        btnVV.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnVVMouseMoved(evt);
            }
        });
        getContentPane().add(btnVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        rbNhomTim.add(rb1);
        rb1.setText("Tìm Tuyệt Đối");
        rb1.setBorder(null);
        getContentPane().add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        rbNhomTim.add(rb2);
        rb2.setSelected(true);
        rb2.setText("Tìm Tương Đối");
        rb2.setBorder(null);
        getContentPane().add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        lbNghia.setEditable(false);
        lbNghia.setColumns(20);
        lbNghia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNghia.setLineWrap(true);
        lbNghia.setRows(5);
        lbNghia.setWrapStyleWord(true);
        lbNghia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbNghia.setEnabled(false);
        jScrollPane2.setViewportView(lbNghia);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 95, 280, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Nen.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 530));

        btnDich.setToolTipText("");
        btnDich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDichMouseClicked(evt);
            }
        });
        getContentPane().add(btnDich, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lsDanhSachValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsDanhSachValueChanged

        result = null;

        try {
            try {
                result = connect.excuteQuery("select * from " + table + " where TuGoc = '" + lsDanhSach.getSelectedValue() + "'");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Lỗi4:" + ex.toString());
            }
            while (result.next()) {
                id = "" + result.getInt("id");
                TuGoc = "" + result.getString("TuGoc");
                Nghia = "" + result.getString("Nghia");
            }
            result.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "" + ex.toString());
        }
        lbNghia.setText(Nghia);
    }//GEN-LAST:event_lsDanhSachValueChanged

    private void txtTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTextCaretUpdate
        if (rb1.isSelected()) {
            search = "";
            search2 = "";
        } else {
            search = "";
            search2 = "%";
        }

        result = null;

        dm.clear();
        lsDanhSach.setModel(dm);

        try {
            sql = "select * from " + table + " where TuGoc like '" + search + "" + txtText.getText() + search2 + "' Order by TuGoc";
            result = connect.excuteQuery(sql);

            try {
                while (result.next()) {
                    dm.addElement(result.getString("TuGoc"));
                }
            } catch (SQLException ex) {
                loadDuLieu();
            }
            result.close();
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, "Lỗi");
        }
        lsDanhSach.setModel(dm);
    }//GEN-LAST:event_txtTextCaretUpdate

    private void btnEVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEVMouseClicked
        table = "engvie";
        loadRong();
        loadDuLieu();
    }//GEN-LAST:event_btnEVMouseClicked

    private void btnVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVEMouseClicked
        table = "vieeng";
        loadRong();
        loadDuLieu();
    }//GEN-LAST:event_btnVEMouseClicked

    private void btnVVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVVMouseClicked
        table = "vievie";
        loadRong();
        loadDuLieu();
    }//GEN-LAST:event_btnVVMouseClicked

    private void btnDichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichMouseClicked
        result = null;
        id = "";

        try {
            try {
                result = connect.excuteQuery("select * from " + table + " where TuGoc = '" + txtText.getText() + "'");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Lỗi4:" + ex.toString());
            }
            if (result.next()) {
                id = "" + result.getInt("id");
                TuGoc = "" + result.getString("TuGoc");
                Nghia = "" + result.getString("Nghia");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "" + ex.toString());
        }
        if (id.equals("")) {
            lbNghia.setText("Không tìm thấy từ này...");
        } else {
            lbNghia.setText(Nghia);
        }
    }//GEN-LAST:event_btnDichMouseClicked

    private void btnEVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEVMouseExited
        btnEV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Eng-Viet1.png")));
    }//GEN-LAST:event_btnEVMouseExited

    private void btnEVMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEVMouseMoved
        btnEV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Eng-Viet2.png")));
    }//GEN-LAST:event_btnEVMouseMoved

    private void btnVEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVEMouseExited
        btnVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Viet-Eng1.png")));
    }//GEN-LAST:event_btnVEMouseExited

    private void btnVEMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVEMouseMoved
        btnVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Viet-Eng2.png")));
    }//GEN-LAST:event_btnVEMouseMoved

    private void btnVVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVVMouseExited
        btnVV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Viet-Viet1.png")));
    }//GEN-LAST:event_btnVVMouseExited

    private void btnVVMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVVMouseMoved
        btnVV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Viet-Viet2.png")));
    }//GEN-LAST:event_btnVVMouseMoved

    public void loadRong() {
        DefaultListModel fm = new DefaultListModel();
        lsDanhSach.setModel(fm);
    }

    public void loadDuLieu() {
        result = null;
        state = null;
        dm.clear();
        lsDanhSach.setModel(dm);

        try {
            result = connect.excuteQuery("select TuGoc from " + table + " Order by TuGoc");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi1:" + ex.toString());
        }
        try {
            while (result.next()) {
                dm.addElement(result.getString("TuGoc"));
            }
        } catch (SQLException ex) {
            loadRong();
            loadDuLieu();
        }
        lsDanhSach.setModel(dm);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDich;
    private javax.swing.JLabel btnEV;
    private javax.swing.JLabel btnVE;
    private javax.swing.JLabel btnVV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea lbNghia;
    private javax.swing.JList lsDanhSach;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.ButtonGroup rbNhomTim;
    private javax.swing.JTextField txtText;
    // End of variables declaration//GEN-END:variables
}
