/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front;

import api.SynthesiserV2;
import back.Database;
import back.Word;
import api.speakOff;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;

/**
 *
 * @author HT3rico
 */
public class DictionaryApplication extends javax.swing.JFrame {
    Database data = new Database();
    Word word= new Word() ;
    DefaultListModel<String> dListModel = new DefaultListModel<>();
    DefaultListModel<String> dListOld = new DefaultListModel<>();
    HashSet <String> old = new HashSet<>();
    
    /**
     * Creates new form DictionaryApplication
     */
    public DictionaryApplication() {
        initComponents();
        seticon();
    }
    
    /**
     * icon 
     */
    private void seticon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon.png")));
    }
    /**
     * Show list từ
     */
    public void showAll() {
        dListModel.clear();
        try ( ResultSet rs = data.exeQ("SELECT word FROM tbl_edict");){
            while (rs.next()) {
                dListModel.addElement(rs.getString("word"));
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error !!! ","Lỗi Dic 4",JOptionPane.ERROR_MESSAGE);
        }
        listWord.setModel(dListModel);
    }
    /**
     * Show lịch sử
     */
    public void showOld() {
        dListOld.clear();
        for (String s : old) {dListOld.addElement(s);}
        listOld.setModel(dListOld);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabble = new javax.swing.JTabbedPane();
        traTu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listWord = new javax.swing.JList<>();
        bClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelOut = new javax.swing.JLabel();
        loa = new javax.swing.JButton();
        bDel = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        textFind = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        listOld = new javax.swing.JList<>();
        Tracuu = new javax.swing.JLabel();
        lichsuTracuu = new javax.swing.JLabel();
        bTrans = new javax.swing.JButton();
        tuVung = new javax.swing.JPanel();
        BG = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Show = new javax.swing.JMenuItem();
        jMenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 150));
        setMinimumSize(new java.awt.Dimension(1050, 700));

        Tabble.setBackground(new java.awt.Color(153, 0, 153));
        Tabble.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        traTu.setBackground(new java.awt.Color(0, 153, 153));
        traTu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        traTu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listWord.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listWord.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        listWord.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listWordValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listWord);

        traTu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 330, 180));

        bClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconReload.jpg"))); // NOI18N
        bClear.setToolTipText("");
        bClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        traTu.add(bClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 40, 40));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        labelOut.setBackground(new java.awt.Color(255, 255, 255));
        labelOut.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelOut.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(labelOut);

        traTu.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 580, 480));

        loa.setText("Phát âm");
        loa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaActionPerformed(evt);
            }
        });
        traTu.add(loa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 50, 40));

        bDel.setText("Xóa");
        bDel.setToolTipText("");
        bDel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelActionPerformed(evt);
            }
        });
        traTu.add(bDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 60, 40));

        bEdit.setText("Sửa từ");
        bEdit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        traTu.add(bEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 60, 40));

        bAdd.setText("Thêm từ");
        bAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });
        traTu.add(bAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 60, 40));

        textFind.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        textFind.setText("Nhập từ cần tìm");
        textFind.setToolTipText(""); // NOI18N
        textFind.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textFindCaretUpdate(evt);
            }
        });
        textFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFindMouseClicked(evt);
            }
        });
        textFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFindKeyPressed(evt);
            }
        });
        traTu.add(textFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 290, 40));

        listOld.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listOld.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listOldValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listOld);

        traTu.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 330, 170));

        Tracuu.setBackground(new java.awt.Color(255, 255, 255));
        Tracuu.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Tracuu.setForeground(new java.awt.Color(255, 255, 204));
        Tracuu.setText("Tra cứu");
        traTu.add(Tracuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lichsuTracuu.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lichsuTracuu.setForeground(new java.awt.Color(255, 255, 204));
        lichsuTracuu.setText("Lịch sử tra cứu");
        traTu.add(lichsuTracuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 250, 30));

        bTrans.setText("Trans");
        bTrans.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        traTu.add(bTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 50, 40));

        Tabble.addTab("Tra Từ", traTu);

        tuVung.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout tuVungLayout = new javax.swing.GroupLayout(tuVung);
        tuVung.setLayout(tuVungLayout);
        tuVungLayout.setHorizontalGroup(
            tuVungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        tuVungLayout.setVerticalGroup(
            tuVungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        Tabble.addTab("Coming soon", tuVung);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ba.jpg"))); // NOI18N
        BG.setToolTipText("");

        jMenu1.setText("File");

        Show.setText("Hiện tất cả các tử");
        Show.setActionCommand("");
        Show.setBorderPainted(true);
        Show.setDoubleBuffered(true);
        Show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowActionPerformed(evt);
            }
        });
        jMenu1.add(Show);

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        about.setText("Author");
        about.setToolTipText("");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenu2.add(about);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BG)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Tabble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tabble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Tabble.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   /**
     * Tắt chương trình
     * @param evt 
     */
    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed
    /**
     * Thêm từ
     * @param evt 
     */
    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        // TODO add your handling code here:
        Them add = new Them();
        //add.setVisible(true);
    }//GEN-LAST:event_bAddActionPerformed
    /**
     * ô tìm kiếm
     * @param evt 
     */
    private void textFindCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_textFindCaretUpdate
        // TODO add your handling code here:
        dListModel.clear();
        String  sql="select * from tbl_edict where word like \"" + textFind.getText() + "%"+"\"";
//       ResultSet result=null;
//        word=new Word();
        if(textFind.getText().isEmpty()){
            labelOut.setText("");
        }
        else{
            try (ResultSet result = data.exeQ(sql)) {
                while (result.next()) {
                    dListModel.addElement(result.getString("word"));
                }
                result.close();
            } 
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Lỗi trong TextFind ","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
        listWord.setModel(dListModel);
        }
    }//GEN-LAST:event_textFindCaretUpdate
    /**
     * Lựa chọn mới trong ListWord
     * @param evt 
     */
    private void listWordValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listWordValueChanged
        if(!listWord.isSelectionEmpty()) {    
            word= data.getword(listWord.getSelectedValue());
            if(!word.getSpelling().isEmpty())
            labelOut.setText("<HTML>"+word.getExplain()+"</HTML>");
        }
//        if(!listWord.isSelectionEmpty()) {
//            word= data.getword(listWord.getSelectedValue());
//            his.put(listWord.getSelectedValue(),1);
//            if(!word.getSpelling().isEmpty())
//            labelOut.setText("<HTML>"+word.getExplain()+"</HTML>");
//        }                                   
    }//GEN-LAST:event_listWordValueChanged
    /**
    * Xóa
    * @param evt 
    */
    private void bDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelActionPerformed
        // TODO add your handling code here:
        if (listWord.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn từ để xóa","Lỗi",JOptionPane.ERROR_MESSAGE);
        } else
        if(!word.getSpelling().isEmpty()) {
            if (old.contains(word.getSpelling())) { 
                old.remove(word.getSpelling()); showOld(); 
            }
            data.delete(word.getSpelling());
            JOptionPane.showMessageDialog(null, "Đã xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            textFind.setText("");
            labelOut.setText("");
            //showAll();    
        }
        else
        JOptionPane.showMessageDialog(null, "Bạn chưa chọn từ để xóa","Lỗi",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_bDelActionPerformed
    /**
    * API speech
    * @param evt 
    */
    private void loaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaActionPerformed
        // TODO add your handling code here:
        if (word.getSpelling().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn từ ","Lỗi",JOptionPane.ERROR_MESSAGE);    
        }
        else {
            SynthesiserV2 speakOn = new SynthesiserV2();
            try {
                 speakOn.speak(word.getSpelling());     
            } 
            catch (JavaLayerException ex) {     
                System.out.println(ex.toString());
                Logger.getLogger(DictionaryApplication.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }//GEN-LAST:event_loaActionPerformed
    /**
    * Sửa
    * @param evt 
    */
    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        Sua s = new Sua();
        if (!word.getSpelling().isEmpty())
            s.setSua(word);
        s.setVisible(true);
    }//GEN-LAST:event_bEditActionPerformed
    /**
     * Click chuột vào ô tìm kiếm
     * @param evt 
     */
    private void textFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFindMouseClicked
        // TODO add your handling code here:
        textFind.setText("");
        labelOut.setText("");
    }//GEN-LAST:event_textFindMouseClicked
    /**
     * Refresh
     * @param evt 
     */
    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        textFind.setText("");
        labelOut.setText("");
    }//GEN-LAST:event_bClearActionPerformed
    /**
     * Nhận phím Enter trong Ô tìm kiếm
     * @param evt 
     */
    private void textFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFindKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (!textFind.getText().isEmpty()) { 
                word = data.getword(textFind.getText());
                if (word.getExplain()!=null){
                    labelOut.setText("<HTML>"+word.getExplain()+"</HTML>"); 
                } 
                else labelOut.setText("Không có từ cần tìm kiếm");
            }
            else {
                labelOut.setText("");
            } 
            if(word.getSpelling()!=null) {
                old.add(word.getSpelling());
                showOld();
            } 
        }
    }//GEN-LAST:event_textFindKeyPressed
    /**
     * List từ cũ
     * @param evt 
     */
    private void listOldValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listOldValueChanged
        // TODO add your handling code here:     
   
            word = data.getword(listOld.getSelectedValue());
            labelOut.setText("<HTML>"+word.getExplain()+"</HTML>");  
    }//GEN-LAST:event_listOldValueChanged
    /**
     * About 
     * @param evt 
     */
    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        About ab = new About();
        ab.setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed

    private void ShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowActionPerformed
        // TODO add your handling code here:
        showAll();
    }//GEN-LAST:event_ShowActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DictionaryApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JMenuItem Show;
    private javax.swing.JTabbedPane Tabble;
    private javax.swing.JLabel Tracuu;
    private javax.swing.JMenuItem about;
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDel;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bTrans;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelOut;
    private javax.swing.JLabel lichsuTracuu;
    private javax.swing.JList<String> listOld;
    private javax.swing.JList<String> listWord;
    private javax.swing.JButton loa;
    private javax.swing.JTextField textFind;
    private javax.swing.JPanel traTu;
    private javax.swing.JPanel tuVung;
    // End of variables declaration//GEN-END:variables
}
