/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front;

import api.SynthesiserV2;
import back.DataBase;
import back.word;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author HT3rico
 */
public class DictionaryApplication extends javax.swing.JFrame {

    /**
     * Creates new form DictionaryApplication
     */
   DataBase connect = new DataBase();
   word word= new word() ;
   DefaultListModel dm = new DefaultListModel();
   SynthesiserV2 synthesizer = new SynthesiserV2();
   int id=139242;
    public DictionaryApplication() {
        initComponents();
        seticon();
        showAll();
       
    }
    private void seticon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabble = new javax.swing.JTabbedPane();
        traTu = new javax.swing.JPanel();
        tfIN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        bClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelOut = new javax.swing.JLabel();
        phatAm = new javax.swing.JButton();
        bDel = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        nangCao = new javax.swing.JPanel();
        tuVung = new javax.swing.JPanel();
        BG = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 150));
        setMinimumSize(new java.awt.Dimension(1050, 700));

        Tabble.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        traTu.setBackground(new java.awt.Color(204, 204, 204));
        traTu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        traTu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfIN.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        tfIN.setText("Nhập từ cần tìm");
        tfIN.setToolTipText("");
        tfIN.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfINCaretUpdate(evt);
            }
        });
        tfIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfINMouseClicked(evt);
            }
        });
        tfIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfINKeyPressed(evt);
            }
        });
        traTu.add(tfIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 170, 30));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        traTu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 260, 370));

        bClear.setText("Clear");
        bClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        traTu.add(bClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 40, 30));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        labelOut.setBackground(new java.awt.Color(255, 255, 255));
        labelOut.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelOut.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(labelOut);

        traTu.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 560, 370));

        phatAm.setText("Phát âm");
        phatAm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        phatAm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phatAmActionPerformed(evt);
            }
        });
        traTu.add(phatAm, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 80, 40));

        bDel.setText("Xóa");
        bDel.setToolTipText("");
        bDel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelActionPerformed(evt);
            }
        });
        traTu.add(bDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 80, 40));

        bEdit.setText("Sửa từ");
        bEdit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        traTu.add(bEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 80, 40));

        bAdd.setText("Thêm từ");
        bAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });
        traTu.add(bAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 80, 40));

        jButton1.setText("Tìm");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        traTu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 40, 30));

        Tabble.addTab("Tra Từ", traTu);

        javax.swing.GroupLayout nangCaoLayout = new javax.swing.GroupLayout(nangCao);
        nangCao.setLayout(nangCaoLayout);
        nangCaoLayout.setHorizontalGroup(
            nangCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1077, Short.MAX_VALUE)
        );
        nangCaoLayout.setVerticalGroup(
            nangCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        Tabble.addTab("Nâng Cao", nangCao);

        tuVung.setFocusTraversalPolicyProvider(true);

        javax.swing.GroupLayout tuVungLayout = new javax.swing.GroupLayout(tuVung);
        tuVung.setLayout(tuVungLayout);
        tuVungLayout.setHorizontalGroup(
            tuVungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1077, Short.MAX_VALUE)
        );
        tuVungLayout.setVerticalGroup(
            tuVungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );

        Tabble.addTab("Học Từ Vựng", tuVung);

        BG.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("??");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tabble)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(BG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tabble, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Tabble.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        tfIN.setText("");
        labelOut.setText("");
    }//GEN-LAST:event_bClearActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        if(!jList1.isSelectionEmpty())
        {    
        ResultSet rs= connect.getword(jList1.getSelectedValue());
       try {
       
               word.setId(rs.getInt("idx"));
               word.setSpelling(rs.getString("word"));
               word.setExplain(rs.getString("detail"));
        } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null,ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
       labelOut.setText("<HTML>"+word.getExplain()+"</HTML>");
    }                                   
    else{
        labelOut.setText("");
    }
    }//GEN-LAST:event_jList1ValueChanged

    private void tfINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfINMouseClicked
        // TODO add your handling code here:
        tfIN.setText("");
    }//GEN-LAST:event_tfINMouseClicked

    private void tfINCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfINCaretUpdate
        // TODO add your handling code here:
        dm.clear();
        jList1.setModel(dm);
        String  sql;
        ResultSet result;
        word=new word();
        if(tfIN.getText().isEmpty()){
            labelOut.setText("");
        }
        else{
        try {
            
            sql="select * from tbl_edict where word like '" + tfIN.getText() + "%"+"'";
            result = connect.excuteQuery(sql);

            try {
                while (result.next()) {
                    dm.addElement(result.getString("word"));
                }
            } catch (SQLException ex) {
                showAll();
            }
            result.close();
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, "Error cmnr !!! ","Lỗi",JOptionPane.ERROR_MESSAGE);
        }
        jList1.setModel(dm);
        }
    }//GEN-LAST:event_tfINCaretUpdate

    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        // TODO add your handling code here:
        Them add = new Them();
        add.setVisible(true);
    }//GEN-LAST:event_bAddActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        Sua edit = new Sua();
        edit.setID(word.getId());
        edit.setVisible(true);
    }//GEN-LAST:event_bEditActionPerformed

    private void bDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelActionPerformed
        // TODO add your handling code here:
        if(!word.spelling.isEmpty())
        {connect.delete(word.spelling);
        tfIN.setText("");
        showAll();
        JOptionPane.showMessageDialog(null, "Đã xóa từ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        JOptionPane.showMessageDialog(null, "Lỗi","Lỗi",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_bDelActionPerformed

    private void phatAmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phatAmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phatAmActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (tfIN.getText()==null) {
             labelOut.setText("");
        } else {
            ResultSet rs= connect.getword(jList1.getSelectedValue());
            try {
               word.setId(rs.getInt("idx"));
               word.setSpelling(rs.getString("word"));
               word.setExplain(rs.getString("detail"));
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        labelOut.setText("<HTML>"+word.getExplain()+"</HTML>");    
        }                               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfINKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfINKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tfIN.getText()==null) {
             labelOut.setText("");
        } else {
            ResultSet rs= connect.getword(jList1.getSelectedValue());
            try {
               word.setId(rs.getInt("idx"));
               word.setSpelling(rs.getString("word"));
               word.setExplain(rs.getString("detail"));
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        labelOut.setText("<HTML>"+word.getExplain()+"</HTML>");    
        } 
        }
    }//GEN-LAST:event_tfINKeyPressed
      public void showAll() {
        ResultSet result = null;
        dm.clear();
       try {
            result = connect.excuteQuery("SELECT word FROM tbl_edict");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi1:" + ex.toString());
        }
        try {
            while (result.next()) {
                dm.addElement(result.getString("word"));
            }
        } catch (SQLException ex) {
            showAll();
        }
        jList1.setModel(dm);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DictionaryApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JTabbedPane Tabble;
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDel;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelOut;
    private javax.swing.JPanel nangCao;
    private javax.swing.JButton phatAm;
    private javax.swing.JTextField tfIN;
    private javax.swing.JPanel traTu;
    private javax.swing.JPanel tuVung;
    // End of variables declaration//GEN-END:variables
}
