/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front;

import api.SynthesiserV2;
import back.Database;
import back.Word;
import api.speakOff;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;

/**
 *
 * @author HT3rico
 */
public class DictionaryApplication extends javax.swing.JFrame {
    Database data = new Database();
    Word word= new Word() ;
    DefaultListModel<String> dListModel = new DefaultListModel<>();
    DefaultListModel<String> dListOldS = new DefaultListModel<>();
    DefaultListModel<String> dListOldD = new DefaultListModel<>();
    HashSet <String> oldS = new HashSet<>();
    HashSet <Word> oldD = new HashSet<>();
    
    
    /**
     * Creates new form DictionaryApplication
     */
    public DictionaryApplication() {
        initComponents();
        seticon();
        showAll();
    }
    
    /**
     * icon 
     */
    private void seticon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon.png")));
    }
    /**
     * Show list từ
     */
    public void showAll() {
        dListModel.clear();
        String sql = "SELECT word FROM Dictionary";
        try ( Connection conn = data.connect(); Statement stmt=conn.createStatement(); ResultSet result = stmt.executeQuery(sql)){
            while (result.next()) {
                dListModel.addElement(result.getString("word"));
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error !!! ","Lỗi Dic 4",JOptionPane.ERROR_MESSAGE);
        }
        listWord.setModel(dListModel);
    }
    /**
     * Show lịch sử
     */
    public void showOldS() {
        dListOldS.clear();
        for (String s : oldS) {dListOldS.addElement(s);}
        listOld.setModel(dListOldS);
        
    }
    public void showOldD() {
        dListOldD.clear();
        for (Word w : oldD) {dListOldD.addElement(w.getSpelling());}
        hisDel.setModel(dListOldD);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabble = new javax.swing.JTabbedPane();
        traTu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listWord = new javax.swing.JList<>();
        bClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelOut = new javax.swing.JLabel();
        loa = new javax.swing.JButton();
        bDel = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bAdd = new javax.swing.JButton();
        textFind = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        listOld = new javax.swing.JList<>();
        Tracuu = new javax.swing.JLabel();
        lichsuTracuu = new javax.swing.JLabel();
        bTrans = new javax.swing.JButton();
        History = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        hisDel = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        honatac = new javax.swing.JButton();
        BG = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictionary_Rico");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(300, 150));
        setMinimumSize(new java.awt.Dimension(1050, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabble.setBackground(new java.awt.Color(153, 0, 153));
        Tabble.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        traTu.setBackground(new java.awt.Color(0, 153, 153));
        traTu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        traTu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        listWord.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listWord.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        listWord.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listWordValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listWord);

        traTu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 320, 210));

        bClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reload_icon.jpg"))); // NOI18N
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });
        traTu.add(bClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 40, 40));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        labelOut.setBackground(new java.awt.Color(255, 255, 255));
        labelOut.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelOut.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(labelOut);

        traTu.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 650, 480));

        loa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/speaker.jpg"))); // NOI18N
        loa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaActionPerformed(evt);
            }
        });
        traTu.add(loa, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 40, 40));

        bDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete_icon.jpg"))); // NOI18N
        bDel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelActionPerformed(evt);
            }
        });
        traTu.add(bDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 40, 40));

        bEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit_icon.jpg"))); // NOI18N
        bEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        traTu.add(bEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 40, 40));

        bAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.jpg"))); // NOI18N
        bAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });
        traTu.add(bAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 40, 40));

        textFind.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        textFind.setText("Nhập từ cần tìm");
        textFind.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textFindCaretUpdate(evt);
            }
        });
        textFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFindMouseClicked(evt);
            }
        });
        textFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFindKeyPressed(evt);
            }
        });
        traTu.add(textFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 290, 40));

        listOld.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listOld.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        listOld.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listOldValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listOld);

        traTu.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 330, 170));

        Tracuu.setBackground(new java.awt.Color(255, 255, 255));
        Tracuu.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Tracuu.setForeground(new java.awt.Color(255, 255, 204));
        Tracuu.setText("Tra cứu");
        traTu.add(Tracuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lichsuTracuu.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lichsuTracuu.setForeground(new java.awt.Color(255, 255, 204));
        lichsuTracuu.setText("Lịch sử tra cứu");
        traTu.add(lichsuTracuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 250, 30));

        bTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/translate_icon_.jpg"))); // NOI18N
        bTrans.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTransActionPerformed(evt);
            }
        });
        traTu.add(bTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 40, 40));

        Tabble.addTab("Tra Từ", traTu);

        History.setBackground(new java.awt.Color(0, 153, 153));
        History.setFocusTraversalPolicyProvider(true);
        History.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hisDel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hisDel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        hisDel.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                hisDelValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(hisDel);

        History.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 230, 390));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Các từ đã xóa");
        History.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 170, -1));

        honatac.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        honatac.setText("Hoàn tác");
        honatac.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        honatac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                honatacActionPerformed(evt);
            }
        });
        History.add(honatac, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 80, 40));

        Tabble.addTab("Lịch sử", History);

        getContentPane().add(Tabble, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 127, 1090, 650));
        Tabble.getAccessibleContext().setAccessibleName("");

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ba.jpg"))); // NOI18N
        BG.setToolTipText("");
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 120));

        jMenu1.setText("File");

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        about.setText("Author");
        about.setToolTipText("");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenu2.add(about);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   /**
     * Tắt chương trình
     * @param evt 
     */
    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed
    /**
     * Thêm từ
     * @param evt 
     */
    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
        // TODO add your handling code here:
        Them add = new Them();
        add.setVisible(true);
    }//GEN-LAST:event_bAddActionPerformed
    /**
     * ô tìm kiếm
     * @param evt 
     */
    private void textFindCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_textFindCaretUpdate
        // TODO add your handling code here:
        dListModel.clear();
        String  sql="select * from Dictionary where word like \"" + textFind.getText() + "%"+"\"";
//       ResultSet result=null;
//        word=new Word();
        if(textFind.getText().isEmpty()){
            labelOut.setText("");
        }
        else{
            try (Connection conn = data.connect(); Statement stmt=conn.createStatement(); ResultSet result = stmt.executeQuery(sql)) {
                while (result.next()) {
                    dListModel.addElement(result.getString("word"));
                }
                result.close();
            } 
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Lỗi trong TextFind ","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
        listWord.setModel(dListModel);
        }
    }//GEN-LAST:event_textFindCaretUpdate
    /**
     * Lựa chọn mới trong ListWord
     * @param evt 
     */
    private void listWordValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listWordValueChanged
        if(!listWord.isSelectionEmpty()) {    
            word = data.getword(listWord.getSelectedValue());
            if(!word.getSpelling().isEmpty())
            labelOut.setText("<HTML>"+word.getExplain()+"</HTML>");
            listOld.clearSelection();
        }                                  
    }//GEN-LAST:event_listWordValueChanged
    /**
    * Xóa
    * @param evt 
    */
    private void bDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelActionPerformed
        // TODO add your handling code here:
        if (listWord.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn từ để xóa","Lỗi",JOptionPane.ERROR_MESSAGE);
        } else
        if(!word.getSpelling().isEmpty()) {
            if (oldS.contains(word.getSpelling())) { 
                oldS.remove(word.getSpelling()); 
                showOldS(); 
            }
            oldD.add(word);
            showOldD();
            data.delete(word.getSpelling());
            
            JOptionPane.showMessageDialog(null, "Đã xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            textFind.setText("");
            labelOut.setText("");
            showAll();    
        }
        else
        JOptionPane.showMessageDialog(null, "Bạn chưa chọn từ để xóa","Lỗi",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_bDelActionPerformed
    /**
    * API speech
    * @param evt 
    */
    private void loaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaActionPerformed
        // TODO add your handling code here:
        if (word.getSpelling().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn từ ","Lỗi",JOptionPane.ERROR_MESSAGE);    
        }
        else {
            SynthesiserV2 speakOn = new SynthesiserV2();
            try {
                 speakOn.speak(word.getSpelling());     
            } 
            catch (JavaLayerException ex) {     
                System.out.println(ex.toString());
                Logger.getLogger(DictionaryApplication.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }//GEN-LAST:event_loaActionPerformed
    /**
    * Sửa
    * @param evt 
    */
    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        if (!listWord.isSelectionEmpty()) {
            word = data.getword(listWord.getSelectedValue());
        } else word.reset();
        Sua s = new Sua();
        if (!word.getSpelling().isEmpty())
            s.setSua(word);
        s.setVisible(true);
    }//GEN-LAST:event_bEditActionPerformed
    /**
     * Click chuột vào ô tìm kiếm
     * @param evt 
     */
    private void textFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFindMouseClicked
        // TODO add your handling code here:
        textFind.setText("");
        labelOut.setText("");
    }//GEN-LAST:event_textFindMouseClicked
    /**
     * Refresh
     * @param evt 
     */
    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        // TODO add your handling code here:
        textFind.setText("");
        labelOut.setText("");
        showAll();
    }//GEN-LAST:event_bClearActionPerformed
    /**
     * Nhận phím Enter trong Ô tìm kiếm
     * @param evt 
     */
    private void textFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFindKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            
            if (!textFind.getText().isEmpty()) { 
                word = data.getword(textFind.getText());
                if (word.getExplain()!=null){
                    labelOut.setText("<HTML>"+word.getExplain()+"</HTML>"); 
                } 
                else labelOut.setText("Không có từ cần tìm kiếm");
            }
            else {
                labelOut.setText("");
            } 
            if(word.getSpelling()!=null) {
                oldS.add(word.getSpelling());
                showOldS();
            } 
        }
    }//GEN-LAST:event_textFindKeyPressed
    /**
     * List từ cũ
     * @param evt 
     */
    private void listOldValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listOldValueChanged
        listWord.clearSelection();
        word = data.getword(listOld.getSelectedValue());
        labelOut.setText("<HTML>"+word.getExplain()+"</HTML>");  
    }//GEN-LAST:event_listOldValueChanged

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        About ab = new About();
        ab.setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed

    private void bTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTransActionPerformed
        // TODO add your handling code here:
        Translate tran = new Translate();
        tran.setVisible(true);
    }//GEN-LAST:event_bTransActionPerformed
    
    private void honatacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_honatacActionPerformed
        // TODO add your handling code here:
        if(!hisDel.isSelectionEmpty()) { 
            oldD.remove(word); 
            data.insert(word);
            showOldD();
            textFind.setText("");
            labelOut.setText("");
            showAll();
            JOptionPane.showMessageDialog(null, "Đã hoàn tác", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_honatacActionPerformed

    private void hisDelValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_hisDelValueChanged
        // TODO add your handling code here:
        if(!hisDel.isSelectionEmpty()) {    
           // word = data.getword(hisDel.getSelectedValue());
            for (Word w : oldD) {
                if (w.getSpelling().equals(hisDel.getSelectedValue())) {
                    word = w;
                    break;
                }
            }
        }  
    }//GEN-LAST:event_hisDelValueChanged
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DictionaryApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JPanel History;
    private javax.swing.JTabbedPane Tabble;
    private javax.swing.JLabel Tracuu;
    private javax.swing.JMenuItem about;
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDel;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bTrans;
    private javax.swing.JList<String> hisDel;
    private javax.swing.JButton honatac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelOut;
    private javax.swing.JLabel lichsuTracuu;
    private javax.swing.JList<String> listOld;
    private javax.swing.JList<String> listWord;
    private javax.swing.JButton loa;
    private javax.swing.JTextField textFind;
    private javax.swing.JPanel traTu;
    // End of variables declaration//GEN-END:variables
}
