/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package front;

import api.GoogleTranslate;
import api.SynthesiserV2;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;

/**
 *
 * @author HT3rico
 */
public class Translate extends javax.swing.JFrame {

    /**
     * Creates new form Translate
     */
    public Translate() {
        initComponents();
        seticon();
        SynthesiserV2 loa= new SynthesiserV2();
        comboIn.setSelectedIndex(1);
    }
    private  String lang = new String();
    private void seticon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/Google_Translate_Icon.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dich = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textFind = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textRs = new javax.swing.JTextArea();
        Change = new javax.swing.JButton();
        comboIn = new javax.swing.JComboBox<>();
        comboOut = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Google Traslate");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(500, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dich.setBackground(new java.awt.Color(255, 255, 255));
        dich.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dich.setText("Dịch");
        dich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dichActionPerformed(evt);
            }
        });
        jPanel1.add(dich, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 200, 90, 42));

        textFind.setColumns(20);
        textFind.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        textFind.setRows(5);
        textFind.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFindKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(textFind);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 331, 264));

        textRs.setColumns(20);
        textRs.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        textRs.setRows(5);
        textRs.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(textRs);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 339, 264));

        Change.setBackground(new java.awt.Color(255, 255, 255));
        Change.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/change_ico.jpg"))); // NOI18N
        Change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeActionPerformed(evt);
            }
        });
        jPanel1.add(Change, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 40, 34));

        comboIn.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        comboIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếng Việt", "Tiếng Anh", "Pháp", "Đức", " " }));
        comboIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboInActionPerformed(evt);
            }
        });
        jPanel1.add(comboIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 40));

        comboOut.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        comboOut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiếng Việt", "Tiếng Anh", "Pháp", "Đức", " " }));
        jPanel1.add(comboOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/speaker.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 40, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/speaker.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dichActionPerformed
        // TODO add your handling code here:
        
        String in = textFind.getText();
     
            if (comboOut.getSelectedIndex() == 0) { lang = "vi";
            }
            if (comboOut.getSelectedIndex() == 1) { lang = "eng";
            }
            if (comboOut.getSelectedIndex() == 2) { lang = "fr";
            }
            if (comboOut.getSelectedIndex() == 3) { lang = "de";
            }
        
        if (!textFind.getText().isEmpty()) {
            try {
                textRs.setText(GoogleTranslate.translate(lang,in));     
            }
            catch(IOException ex){
                JOptionPane.showMessageDialog(null, "Lỗi dịch anh -> việt !!! ","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_dichActionPerformed

    private void ChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeActionPerformed
        // TODO add your handling code here:
        int in = comboIn.getSelectedIndex();
        int out = comboOut.getSelectedIndex();
  
        comboOut.setSelectedIndex(in);
        comboIn.setSelectedIndex(out);
    }//GEN-LAST:event_ChangeActionPerformed

    private void textFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFindKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            String in = textFind.getText();
           
            if (comboOut.getSelectedIndex() == 0) { lang = "vi";
            }
            if (comboOut.getSelectedIndex() == 1) { lang = "eng";
            }
            if (comboOut.getSelectedIndex() == 2) { lang = "fr";
            }
            if (comboOut.getSelectedIndex() == 3) { lang = "de";
            }

       
            if (!textFind.getText().isEmpty()) {
                try {
                    textRs.setText(GoogleTranslate.translate(lang,in));     
                }
                catch(IOException ex){
                    JOptionPane.showMessageDialog(null, "Lỗi dịch anh -> việt !!! ","Lỗi",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_textFindKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!textRs.getText().isEmpty()) {
            SynthesiserV2 speaker = new SynthesiserV2();
            try {
                 speaker.speak(textRs.getText());     
            } 
            catch (JavaLayerException ex) {     
                System.out.println(ex.toString());
                Logger.getLogger(DictionaryApplication.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (!textFind.getText().isEmpty()) {
            SynthesiserV2 speaker = new SynthesiserV2();
            try {
                 speaker.speak(textFind.getText());     
            } 
            catch (JavaLayerException ex) {     
                System.out.println(ex.toString());
                Logger.getLogger(DictionaryApplication.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboInActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Translate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Translate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Translate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Translate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Translate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Change;
    private javax.swing.JComboBox<String> comboIn;
    private javax.swing.JComboBox<String> comboOut;
    private javax.swing.JButton dich;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textFind;
    private javax.swing.JTextArea textRs;
    // End of variables declaration//GEN-END:variables
}
