/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package servertudien;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Administrator
 */
public class Main extends javax.swing.JFrame {

    KetNoi connect = new KetNoi("localhost", "root", "", "csdl");
    DefaultListModel dm = new DefaultListModel();
    ResultSet result = null;
    Statement state = null;
    String table = "engvie";
    String id;
    String TuGoc;
    String Nghia;
    String search = "";
    String search2 = "";
    JTextArea lbNghia = new JTextArea();
    String cTrinh = "";
    String sql = "";
    String kiemtra = "";

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        centerLocation();
        loadDuLieu();
        function();
        HideCN();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbNhomTim = new javax.swing.ButtonGroup();
        txtText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsDanhSach = new javax.swing.JList();
        btnThem = new javax.swing.JLabel();
        btnChinhSua = new javax.swing.JLabel();
        btnXoa = new javax.swing.JLabel();
        btnEV = new javax.swing.JLabel();
        btnVE = new javax.swing.JLabel();
        btnVV = new javax.swing.JLabel();
        pnChucNang = new javax.swing.JPanel();
        txtTuGoc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNghia = new javax.swing.JTextArea();
        btnHoanThanh = new javax.swing.JLabel();
        btnHuy = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnDich = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương Trình Từ Điển Trực Tuyến");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTextCaretUpdate(evt);
            }
        });
        getContentPane().add(txtText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 220, -1));

        lsDanhSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lsDanhSach.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lsDanhSach.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsDanhSachValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lsDanhSach);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 220, 300));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Them1.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemMouseExited(evt);
            }
        });
        btnThem.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnThemMouseMoved(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 60, 40));

        btnChinhSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/sua1.png"))); // NOI18N
        btnChinhSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChinhSuaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChinhSuaMouseExited(evt);
            }
        });
        btnChinhSua.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnChinhSuaMouseMoved(evt);
            }
        });
        getContentPane().add(btnChinhSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 50, 30));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/xoa1.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaMouseExited(evt);
            }
        });
        btnXoa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnXoaMouseMoved(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 180, 60, 40));

        btnEV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Eng-Viet1.png"))); // NOI18N
        btnEV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEVMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEVMouseClicked(evt);
            }
        });
        btnEV.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEVMouseMoved(evt);
            }
        });
        getContentPane().add(btnEV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        btnVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/VIet-Eng1.png"))); // NOI18N
        btnVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVEMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVEMouseClicked(evt);
            }
        });
        btnVE.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnVEMouseMoved(evt);
            }
        });
        getContentPane().add(btnVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        btnVV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Viet-Viet1.png"))); // NOI18N
        btnVV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVVMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVVMouseClicked(evt);
            }
        });
        btnVV.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnVVMouseMoved(evt);
            }
        });
        getContentPane().add(btnVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        pnChucNang.setPreferredSize(new java.awt.Dimension(419, 344));

        txtNghia.setColumns(20);
        txtNghia.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtNghia.setRows(5);
        txtNghia.setWrapStyleWord(true);
        txtNghia.setCaretColor(new java.awt.Color(0, 0, 204));
        jScrollPane2.setViewportView(txtNghia);
        txtNghia.getAccessibleContext().setAccessibleParent(pnChucNang);

        btnHoanThanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/btnHoanThanh1.png"))); // NOI18N
        btnHoanThanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHoanThanhMouseClicked(evt);
            }
        });

        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/btnHuy1.png"))); // NOI18N
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/NenPn.png"))); // NOI18N
        jLabel2.setText("Từ Gốc:");
        jLabel2.setToolTipText("");

        jLabel3.setText("Nghĩa Của Từ:");

        jLabel4.setText("Từ Gốc:");

        javax.swing.GroupLayout pnChucNangLayout = new javax.swing.GroupLayout(pnChucNang);
        pnChucNang.setLayout(pnChucNangLayout);
        pnChucNangLayout.setHorizontalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(btnHoanThanh, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(txtTuGoc, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnChucNangLayout.setVerticalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnHuy))
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(btnHoanThanh))
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(txtTuGoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnChucNang, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 280, 370));

        rbNhomTim.add(rb1);
        rb1.setText("Tìm Tuyệt Đối");
        rb1.setBorder(null);
        getContentPane().add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        rbNhomTim.add(rb2);
        rb2.setSelected(true);
        rb2.setText("Tìm Tương Đối");
        rb2.setBorder(null);
        getContentPane().add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Nen.png"))); // NOI18N
        jLabel1.setText("Dịch");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 530));

        btnDich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/btnDich.png"))); // NOI18N
        btnDich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDichMouseClicked(evt);
            }
        });
        getContentPane().add(btnDich, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 60, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lsDanhSachValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsDanhSachValueChanged
        lbNghia.setVisible(true);
        pnChucNang.add(lbNghia);
        HideCN();
        result = null;

        try {
            try {
                result = connect.excuteQuery("select * from " + table + " where TuGoc = '" + lsDanhSach.getSelectedValue() + "'");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Lỗi4:" + ex.toString());
            }
            while (result.next()) {
                id = "" + result.getInt("id");
                TuGoc = "" + result.getString("TuGoc");
                Nghia = "" + result.getString("Nghia");
            }
            result.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "" + ex.toString());
        }
        lbNghia.setText(Nghia);
    }//GEN-LAST:event_lsDanhSachValueChanged

    private void txtTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTextCaretUpdate
        if (rb1.isSelected()) {
            search = "";
            search2 = "";
        } else {
            search = "";
            search2 = "%";
        }

        result = null;
        lbNghia.setVisible(true);
        HideCN();
        dm.clear();
        lsDanhSach.setModel(dm);

        try {
            sql = "select * from " + table + " where TuGoc like '" + search + "" + txtText.getText() + search2 + "' Order by TuGoc";
            result = connect.excuteQuery(sql);

            try {
                while (result.next()) {
                    dm.addElement(result.getString("TuGoc"));
                }
            } catch (SQLException ex) {
                loadDuLieu();
            }
            result.close();
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            //JOptionPane.showMessageDialog(null, "Lỗi");
        }
        lsDanhSach.setModel(dm);
    }//GEN-LAST:event_txtTextCaretUpdate

    private void btnThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseClicked
        lbNghia.setVisible(false);
        ShowCN();
        cTrinh = "Them";
        txtTuGoc.setText("");
        txtNghia.setText("");
    }//GEN-LAST:event_btnThemMouseClicked

    private void btnHoanThanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoanThanhMouseClicked
        if (txtTuGoc.getText().equals("") || txtNghia.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Lỗi bạn chưa nhập đầy đủ dữ liệu");
        } else {
            switch (cTrinh) {
                case "Them":
                    result = null;
                    state = null;
                    try {
                        state = connect.getStatement();

                        sql = "insert into " + table + " values('" + txtTuGoc.getText() + "','" + txtNghia.getText() + "',NULL)";

                        kiemtra = "select TuGoc from " + table + " where TuGoc='" + txtTuGoc.getText() + "'";
                        try {
                            result = connect.excuteQuery(kiemtra);
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(null, "Lỗi:" + ex.toString());
                        }
                        try {
                            if (result.next()) {
                                JOptionPane.showMessageDialog(null, "Lỗi bạn đã nhập trùng");
                                result.close();
                            } else {
                                state.executeUpdate(sql);
                                HideCN();
                                JOptionPane.showMessageDialog(null, "Thêm Thành Công");
                            }
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(null, "Lỗi2:" + ex.toString());
                        }

                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Lỗi3:" + ex.toString());
                    }
                    try {
                        result.close();
                        state.close();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Lỗi:" + ex.toString());
                    }
                    break;
                case "Chinh":
                    result = null;
                    state = null;
                    try {
                        lbNghia.setText(txtNghia.getText());
                        state = connect.getStatement();
                        sql = "update " + table + " set Tugoc='" + txtTuGoc.getText() + "',Nghia='" + txtNghia.getText() + "' where ID='" + id + "'";
                        state.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Đã Chỉnh Sửa Thành Công");
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(null, "Lỗi:" + ex.toString());
                    }
                    break;
            }
        }
        loadRong();
        loadDuLieu();
    }//GEN-LAST:event_btnHoanThanhMouseClicked

    private void btnChinhSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChinhSuaMouseClicked
        lbNghia.setVisible(false);
        ShowCN();
        cTrinh = "Chinh";

        txtTuGoc.setText(TuGoc);
        txtNghia.setText(Nghia);
    }//GEN-LAST:event_btnChinhSuaMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        state = null;
        result = null;

        int answer = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa từ " + TuGoc + " không ?", "Cảnh Báo", JOptionPane.YES_NO_OPTION);
        if (answer == JOptionPane.YES_OPTION) {
            try {

                state = connect.getStatement();
                sql = "delete from " + table + " where id='" + id + "'";
                state.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Đã Xóa");


            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Lỗi12:" + ex.toString());
            }

            try {
                state.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Lỗi: " + ex.toString());
            }

        } else {
        }

        lbNghia.setText("");
        loadRong();
        loadDuLieu();
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseClicked
        HideCN();
        lbNghia.setVisible(true);
    }//GEN-LAST:event_btnHuyMouseClicked
    /*
     --
     ---------------------------------------------------------------------
     -- Loại Từ Điển
     ---------------------------------------------------------------------
     --
     */
    private void btnEVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEVMouseClicked
        table = "engvie";
        loadRong();
        loadDuLieu();
    }//GEN-LAST:event_btnEVMouseClicked

    private void btnVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVEMouseClicked
        table = "vieeng";
        loadRong();
        loadDuLieu();
    }//GEN-LAST:event_btnVEMouseClicked

    private void btnVVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVVMouseClicked
        table = "vievie";
        loadRong();
        loadDuLieu();
    }//GEN-LAST:event_btnVVMouseClicked
    /*
     --
     ---------------------------------------------------------------------
     -- Đồ Họa
     ---------------------------------------------------------------------
     --
     */
    // <editor-fold defaultstate="collapsed" desc="Tên Từ Điển">
    private void btnEVMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEVMouseMoved
        btnEV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Eng-Viet2.png")));
    }//GEN-LAST:event_btnEVMouseMoved

    private void btnEVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEVMouseExited
        btnEV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Eng-Viet1.png")));
    }//GEN-LAST:event_btnEVMouseExited

    private void btnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseExited
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/xoa1.png")));
    }//GEN-LAST:event_btnXoaMouseExited

    private void btnXoaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseMoved
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/xoa2.png")));
    }//GEN-LAST:event_btnXoaMouseMoved

    private void btnChinhSuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChinhSuaMouseExited
        btnChinhSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/sua1.png")));
    }//GEN-LAST:event_btnChinhSuaMouseExited

    private void btnChinhSuaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChinhSuaMouseMoved
        btnChinhSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/sua2.png")));
    }//GEN-LAST:event_btnChinhSuaMouseMoved

    private void btnThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseExited
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Them1.png")));
    }//GEN-LAST:event_btnThemMouseExited

    private void btnThemMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseMoved
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Them2.png")));
    }//GEN-LAST:event_btnThemMouseMoved

    private void btnDichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDichMouseClicked
        lbNghia.setVisible(true);
        pnChucNang.add(lbNghia);
        HideCN();

        result = null;
        id = "";

        try {
            try {
                result = connect.excuteQuery("select * from " + table + " where TuGoc = '" + txtText.getText() + "'");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Lỗi4:" + ex.toString());
            }
            if (result.next()) {
                id = "" + result.getInt("id");
                TuGoc = "" + result.getString("TuGoc");
                Nghia = "" + result.getString("Nghia");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "" + ex.toString());
        }
        if (id.equals("")) {
            lbNghia.setText("Không tìm thấy từ này...");
        } else {
            lbNghia.setText(Nghia);
        }
    }//GEN-LAST:event_btnDichMouseClicked

    private void btnVEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVEMouseExited
        btnVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Viet-Eng1.png")));
    }//GEN-LAST:event_btnVEMouseExited

    private void btnVEMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVEMouseMoved
        btnVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Viet-Eng2.png")));
    }//GEN-LAST:event_btnVEMouseMoved

    private void btnVVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVVMouseExited
        btnVV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Viet-Viet1.png")));
    }//GEN-LAST:event_btnVVMouseExited

    private void btnVVMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVVMouseMoved
        btnVV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/Viet-Viet2.png")));
    }//GEN-LAST:event_btnVVMouseMoved
// </editor-fold>
    // <editor-fold defaultstate="collapsed" desc="Load">

    public void function() {
        lbNghia.setLocation(0, 0);
        lbNghia.setSize(pnChucNang.getSize());
        lbNghia.setFont(new java.awt.Font("Tahoma", 0, 14));
        lbNghia.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbNghia.setLineWrap(true);
        lbNghia.setWrapStyleWord(true);
        lbNghia.setEditable(false);
        lbNghia.setLayout(null);
    }

    public void HideCN() {
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jScrollPane2.setVisible(false);
        txtTuGoc.setVisible(false);
        txtNghia.setVisible(false);
        btnHuy.setVisible(false);
        btnHoanThanh.setVisible(false);
    }

    public void ShowCN() {
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jScrollPane2.setVisible(true);
        txtTuGoc.setVisible(true);
        txtNghia.setVisible(true);
        btnHuy.setVisible(true);
        btnHoanThanh.setVisible(true);
    }

    public void loadRong() {
        DefaultListModel fm = new DefaultListModel();
        lsDanhSach.setModel(fm);
    }

    public void loadDuLieu() {
        result = null;
        state = null;
        dm.clear();
        lsDanhSach.removeAll();

        try {
            result = connect.excuteQuery("select TuGoc from " + table + " Order by TuGoc");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi1:" + ex.toString());
        }
        try {
            while (result.next()) {
                dm.addElement(result.getString("TuGoc"));
            }
        } catch (SQLException ex) {
            loadRong();
            loadDuLieu();
        }
        lsDanhSach.setModel(dm);
        lbNghia.setText("");
    }
// </editor-fold>

    /**
     * @param args the command line arguments
     */
    private void centerLocation() {
        // get screen size
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        // get screen width, height
        int w = this.getSize().width;
        int h = this.getSize().height;
        // position x, y
        int x = (d.width - w) / 2;
        int y = (d.height - h) / 2;
        // set location for frame by position x, y
        this.setLocation(x, y);
    }

    public static void main(String args[]) {


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                 new Main().setVisible(true);
            }
        });


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnChinhSua;
    private javax.swing.JLabel btnDich;
    private javax.swing.JLabel btnEV;
    private javax.swing.JLabel btnHoanThanh;
    private javax.swing.JLabel btnHuy;
    private javax.swing.JLabel btnThem;
    private javax.swing.JLabel btnVE;
    private javax.swing.JLabel btnVV;
    private javax.swing.JLabel btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lsDanhSach;
    private javax.swing.JPanel pnChucNang;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.ButtonGroup rbNhomTim;
    private javax.swing.JTextArea txtNghia;
    private javax.swing.JTextField txtText;
    private javax.swing.JTextField txtTuGoc;
    // End of variables declaration//GEN-END:variables
}
