/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import API.SynthesiserV2;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;

/**
 *
 * @author HT3rico
 */
public class Screen extends javax.swing.JFrame {

    DictionaryManegement connect = new DictionaryManegement();
    Word word= new Word() ;
    DefaultListModel dm = new DefaultListModel();
    SynthesiserV2 synthesizer = new SynthesiserV2();
    int id=139242;
    public Screen() {
       initComponents();
       loadDuLieu();
       
    }
    private Object test1;
    private Object test2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAdd = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        bDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tfEnter = new javax.swing.JTextField();
        jScrollPan = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        backgr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictionary_Rico");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/img/add.png"))); // NOI18N
        bAdd.setToolTipText("Thêm từ");
        bAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddActionPerformed(evt);
            }
        });
        getContentPane().add(bAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 30, -1));

        bEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/img/edit.png"))); // NOI18N
        bEdit.setToolTipText("Sửa từ");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        getContentPane().add(bEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 30, -1));

        bDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/img/delete.png"))); // NOI18N
        bDelete.setToolTipText("Xóa từ");
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(bDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 50, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/img/volum.png"))); // NOI18N
        jButton1.setToolTipText("Nghe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 30, -1));

        jButton2.setText("Xóa");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, -1));

        tfEnter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tfEnter.setText("Nhập từ");
        tfEnter.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfEnterCaretUpdate(evt);
            }
        });
        getContentPane().add(tfEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 176, -1));

        jList1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jScrollPan.setViewportView(jList1);

        getContentPane().add(jScrollPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 230));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 670, 480));

        jRadioButton2.setText("Tìm tương đối");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        rb1.setText("Search");
        getContentPane().add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jLabel1.setText("Chuyển");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, -1, -1));

        backgr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/img/Back.jpg"))); // NOI18N
        getContentPane().add(backgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private void bAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddActionPerformed
      // TODO add your handling code here:
        add add = new add();
        add.setVisible(true);
    }//GEN-LAST:event_bAddActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed

        edit edit = new edit();
        edit.setID(word.id);
        edit.setVisible(true);
    }//GEN-LAST:event_bEditActionPerformed
private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {                                    
        // TODO add your handling code here:
    if(!jList1.isSelectionEmpty())
        {    
        ResultSet rs= connect.getword(jList1.getSelectedValue());
       try {
           while(rs.next()){
               word.id =rs.getInt("idx");
               word.spelling=rs.getString("word");
               word.explain= rs.getString("detail");
                 
           }
           rs.close();
       } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
       }
       jLabel2.setText("<HTML>"+word.explain+"</HTML>");
    }                                   
    else{
        jLabel2.setText("");
    }
    }
    private void tfEnterCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfEnterCaretUpdate
        // TODO add your handling code here:
        dm.clear();
        jList1.setModel(dm);
        String  sql;
        ResultSet result;
        word=new Word();
        if(tfEnter.getText().isEmpty()){
            backgr.setText("");
        }
        else{
        try {
            if(rb1.isSelected())
                sql = "select * from tbl_edict where word like '"  + tfEnter.getText() + "'" ;
            else
                sql="select * from tbl_edict where word like '" + tfEnter.getText() + "%"+"'";
            result = connect.excuteQuery(sql);

            try {
                while (result.next()) {
                    dm.addElement(result.getString("word"));
                }
            } catch (SQLException ex) {
                loadDuLieu();
            }
            result.close();
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, "Có lỗi trong việc lấy dữ liệu, thành thật xin lỗi! ","Lỗi",JOptionPane.ERROR_MESSAGE);
        }
        jList1.setModel(dm);
        }
    }//GEN-LAST:event_tfEnterCaretUpdate

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        // TODO add your handling code here:
        if(!word.spelling.isEmpty())
        {connect.delete(word.spelling);
        JOptionPane.showMessageDialog(null, "Xóa từ thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        JOptionPane.showMessageDialog(null, "Bạn chưa chọn từ để xóa","Lỗi",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_bDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
                synthesizer.speak(word.spelling);
                
           } catch (JavaLayerException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tfEnter.setText("");
        jLabel1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed
    public void loadDuLieu() {
        ResultSet result = null;
        dm.clear();
       try {
            result = connect.excuteQuery("SELECT word FROM tbl_edict");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi1:" + ex.toString());
        }
        try {
            while (result.next()) {
                dm.addElement(result.getString("word"));
            }
        } catch (SQLException ex) {
            loadDuLieu();
        }
        jList1.setModel(dm);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Screen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdd;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bEdit;
    private javax.swing.JLabel backgr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPan;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JTextField tfEnter;
    // End of variables declaration//GEN-END:variables
}
